### ISSUE TITLE
[FEAT] As a developer, I want to know if my Magento VCS `config.php` is in sync with what would be deployed.

### ISSUE THREAD

**Issue by damienwebdev** [mage-os/github-actions#123]
# :bulb: Feature request

## Feature Name
`check-config`

## The Desired Behavior
I would like to be able to use a Github action called `check-config` which verifies (without having an associated database connection) that my local `config.php` is in sync with what would result from `setup:upgrade`. 

## Your Use Case
I very often find that developers forget to commit their updates to `config.php`. If you're doing `di:compile` ahead of time in docker for example, then your build output will not be what you expect if your `config.php` isn't up to date.

cc: @vitaliy-golomoziy

**Comment by convenient** [comment]
I have this in circleci
```yaml
      - run:
          name: "Ensure app/etc/config.php is up to date"
          command: php -d memory_limit=-1 bin/magento module:config:status
```
