### ISSUE TITLE
[FEAT] Add support for `magento/magento-cloud-metapackage` in `get-magento-version`

### ISSUE THREAD

**Issue by damienwebdev** [mage-os/github-actions#126]
# :bulb: Feature request

## Feature Name
I was trying to use these actions with a Magento Cloud project. Unfortunately, we don't compute `get-magento-version` that key for stores.

## The Desired Behavior

I would like to be able to drop an action like the following into my Github actions and retrieve the correct Magento version.
```yml
steps:
- uses: mage-os/github-actions/get-magento-version@main
  id: get-magento-version
      with:
          working-directory: ${{ secrets.GITHUB_WORKSPACE }}
```

## Your Use Case
As a developer, I would like to be able to compute the currently installed Magento version for Magento Cloud projects from `composer.json` or `composer.lock`.
