### ISSUE TITLE
[FEAT] Add new `fail_on_warnings` to the `coding-standard` action

### ISSUE THREAD

**Issue by damienwebdev** [mage-os/github-actions#130]
# :bulb: Feature request

## Feature Name
Allow Codesniff warnings

## The Desired Behavior
As a developer, when I have PHPCS warnings, I don't necessarily want my CI pipeline to error. I would like something like:

```yml
fail_on_warnings:
    description: 'Whether action should fail on warnings or not, default to true (fails)'
    required: false
```

as an input to this action.

## Your Use Case
As a developer, I want my ci pipeline to pass if there are PHPCS warnings but no errors.
