### ISSUE TITLE
[RFC] Removal of publicly-facing workflows

### ISSUE THREAD

**Issue by damienwebdev** [mage-os/github-actions#140]
# :bulb: Feature request

## Feature Name
No public workflows.

## The Desired Behavior
I would like for there to be no workflows available in the public API of this repo.

## Your Use Case
Previously, we exposed [an `integration` workflow ](https://github.com/mage-os/github-actions/blob/main/.github/workflows/integration.yaml) that others could use to run integration tests. 

This is rather brittle and is too inflexible for more complex use-cases like #14 or supporting Opensearch or any search driver/database service/caching service, etc.

The reason we had workflows in the first place was so that I could encapsulate the `services` logic that the workflows use. It turns out that we don't need to [do this at all.](https://github.com/mage-os/github-actions/pull/139)

Instead, I would like to expose an action with a usage interface like:

```
jobs:
    compute_env:
      runs-on: ubuntu-latest
      outputs:
        matrix: ${{ steps.supported-services.outputs.services }}
      steps:
        - uses: actions/checkout@v3

        - uses: mage-os/github-actions/supported-version@main
           id: supported-version

        - uses: mage-os/github-actions/supported-services@main
           id: supported-services
           with:
               configurations: '?'
    
    test
        needs: [compute_matrix]
        services: ${{ fromJson(needs.compute_env.outputs.services ) }}
        steps:
           - run: echo "Run tests..."
             shell: bash
```

I would like some feedback on what the API of such an action could be.

My current struggle is to find an input that allows controlled flexibility.

`configuration` - `minimal`, `common`, `full`, `commerce-cloud`, `custom`

## Prior Work
#14
#139
